"""Add synthesis junction and relationships

Revision ID: 12f7e8eb03d3
Revises: 17d85c749788
Create Date: 2026-02-28 02:40:46.947882

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '12f7e8eb03d3'
down_revision: Union[str, Sequence[str], None] = '17d85c749788'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('synthesisdocumentlink',
    sa.Column('synthesis_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ),
    sa.ForeignKeyConstraint(['synthesis_id'], ['synthesis.id'], ),
    sa.PrimaryKeyConstraint('synthesis_id', 'document_id')
    )
    op.drop_column('synthesis', 'document_ids')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('synthesis', sa.Column('document_ids', sa.VARCHAR(), nullable=False))
    op.drop_table('synthesisdocumentlink')
    # ### end Alembic commands ###
