"""add_refresh_tokens_table

Revision ID: 97697c7751ca
Revises: 12f7e8eb03d3
Create Date: 2026-03-03 21:07:04.731879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '97697c7751ca'
down_revision: Union[str, Sequence[str], None] = '12f7e8eb03d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refreshtoken',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('token', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('family', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refreshtoken_family'), 'refreshtoken', ['family'], unique=False)
    op.create_index(op.f('ix_refreshtoken_token'), 'refreshtoken', ['token'], unique=True)
    op.create_index(op.f('ix_refreshtoken_user_id'), 'refreshtoken', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_refreshtoken_user_id'), table_name='refreshtoken')
    op.drop_index(op.f('ix_refreshtoken_token'), table_name='refreshtoken')
    op.drop_index(op.f('ix_refreshtoken_family'), table_name='refreshtoken')
    op.drop_table('refreshtoken')
    # ### end Alembic commands ###
